SET VECTORCAST_DIR=C:\Vcast64z
SET PATH=C:\GHS\multi_614;C:\GHS\comp_201354;%PATH%
SET VC_GHS_OS_DIR=C:\GHS\INTEGRITY\5.0.1.1\ppc-w
%VECTORCAST_DIR%\CLICAST /L:CPLUSPLUS tools execute commands.tmp false
